//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueIQ_Neuware.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueIQ_Neuware.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application stopped successfully.
        /// </summary>
        internal static string APP_STOPPED {
            get {
                return ResourceManager.GetString("APP_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking next device.
        /// </summary>
        internal static string BOOK_NEXT {
            get {
                return ResourceManager.GetString("BOOK_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The devices have been booked, please check the excel file to confirm.
        /// </summary>
        internal static string BOOKED_ALL_MESS {
            get {
                return ResourceManager.GetString("BOOKED_ALL_MESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices have been added.
        /// </summary>
        internal static string BOOKED_ALL_STATUS {
            get {
                return ResourceManager.GetString("BOOKED_ALL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BROWSE {
            get {
                return ResourceManager.GetString("BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create excel template.
        /// </summary>
        internal static string CREATE_EXCEL_TEMPLATE {
            get {
                return ResourceManager.GetString("CREATE_EXCEL_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Type.
        /// </summary>
        internal static string CREDIT_TYPE {
            get {
                return ResourceManager.GetString("CREDIT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: .
        /// </summary>
        internal static string ERROR_GEN_MESS {
            get {
                return ResourceManager.GetString("ERROR_GEN_MESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        internal static string ERROR_GEN_STATUS {
            get {
                return ResourceManager.GetString("ERROR_GEN_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns should be:
        ///A:Serial number
        ///B:Part number.
        /// </summary>
        internal static string EXCEL_FILE_TIP1 {
            get {
                return ResourceManager.GetString("EXCEL_FILE_TIP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns should be:
        ///A:Old scan ID
        ///B:New swap serial.
        /// </summary>
        internal static string EXCEL_FILE_TIP2 {
            get {
                return ResourceManager.GetString("EXCEL_FILE_TIP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all fields before proceeding..
        /// </summary>
        internal static string FILL_FIELDS_MESS {
            get {
                return ResourceManager.GetString("FILL_FIELDS_MESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supports 3 modes:
        ///-Booking new stock
        ///-Booking B2B devices
        ///-creating manual outbound orders
        ///
        ///For questions or requests please contact:
        ///nAnil.chikmetoglou@ingrammicro.com&quot;.
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill a sorting location.
        /// </summary>
        internal static string LOCATION_TIP {
            get {
                return ResourceManager.GetString("LOCATION_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Check username and password.
        /// </summary>
        internal static string LOG_FAIL_MESS {
            get {
                return ResourceManager.GetString("LOG_FAIL_MESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LOG_FAIL_STATUS {
            get {
                return ResourceManager.GetString("LOG_FAIL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in.
        /// </summary>
        internal static string LOGGED {
            get {
                return ResourceManager.GetString("LOGGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        internal static string LOGGING {
            get {
                return ResourceManager.GetString("LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page took too long to load.
        /// </summary>
        internal static string LONG_LOAD {
            get {
                return ResourceManager.GetString("LONG_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Information.
        /// </summary>
        internal static string MISSING_INFO {
            get {
                return ResourceManager.GetString("MISSING_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating next outbound Order.
        /// </summary>
        internal static string NEXT_ORDER {
            get {
                return ResourceManager.GetString("NEXT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PASS {
            get {
                return ResourceManager.GetString("PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill a valid Pono or Job ID number.
        /// </summary>
        internal static string PONO_TIP {
            get {
                return ResourceManager.GetString("PONO_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program finished.
        /// </summary>
        internal static string PRO_FINISHED {
            get {
                return ResourceManager.GetString("PRO_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to program stopped.
        /// </summary>
        internal static string PROGRAM_STOPPED {
            get {
                return ResourceManager.GetString("PROGRAM_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a mode before proceeding..
        /// </summary>
        internal static string SELECT_MODE_MESS {
            get {
                return ResourceManager.GetString("SELECT_MODE_MESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose task.
        /// </summary>
        internal static string TASK {
            get {
                return ResourceManager.GetString("TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
    }
}
